//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWLMergeBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JWLMergeBot.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 🗑 Delete file after send: {0}.
        /// </summary>
        internal static string auto_delete {
            get {
                return ResourceManager.GetString("auto_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connection with the bot has been lost and it will be re-established when possible.
        /// </summary>
        internal static string bot_disconnected {
            get {
                return ResourceManager.GetString("bot_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bot info.
        /// </summary>
        internal static string bot_info {
            get {
                return ResourceManager.GetString("bot_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a JWLMergeBot version: {0}\nJWLMerge version: {1}\nRepository and infos: https://gitlab.com/AlessandroLucchet/JWLMergeBot.
        /// </summary>
        internal static string bot_info_details {
            get {
                return ResourceManager.GetString("bot_info_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Started JWLMergeBot v{0}.
        /// </summary>
        internal static string bot_started {
            get {
                return ResourceManager.GetString("bot_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ❗️ I&apos;m already working on another file… Please, send one file at once 😅\nThe file {0} would be ignored 🙄.
        /// </summary>
        internal static string busy {
            get {
                return ResourceManager.GetString("busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ❌ Cannot download file. Please send it back later.
        /// </summary>
        internal static string cannot_download_file_retry {
            get {
                return ResourceManager.GetString("cannot_download_file_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 💬 Change language.
        /// </summary>
        internal static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 💬 Change language: 🇬🇧.
        /// </summary>
        internal static string change_language_detail {
            get {
                return ResourceManager.GetString("change_language_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ⚙️ Change settings.
        /// </summary>
        internal static string change_settings {
            get {
                return ResourceManager.GetString("change_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0}{1} (ChatId: {2}).
        /// </summary>
        internal static string chat_name {
            get {
                return ResourceManager.GetString("chat_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ⚙️ Configuration file &quot;config.json&quot; not found.
        /// </summary>
        internal static string config_not_found {
            get {
                return ResourceManager.GetString("config_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete stored file.
        /// </summary>
        internal static string delete_file {
            get {
                return ResourceManager.GetString("delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 🗑 Stored file deleted.
        /// </summary>
        internal static string file_deleted {
            get {
                return ResourceManager.GetString("file_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ❗️ Error while opening the file: {0}.
        /// </summary>
        internal static string file_error {
            get {
                return ResourceManager.GetString("file_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        internal static string file_info {
            get {
                return ResourceManager.GetString("file_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ℹ️ Some info regarding the file:\nFile size: {0}\nNotes count: {1}\nBookmarks count: {2}\nHighlights count: {3}\nTags count: {4}\nPlaylists count: None! I don&apos;t support them.
        /// </summary>
        internal static string file_info_details {
            get {
                return ResourceManager.GetString("file_info_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 👾 I&apos;ve no file in memory.
        /// </summary>
        internal static string file_not_exists {
            get {
                return ResourceManager.GetString("file_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 🔑 Invalid token! Please, verify that in the &quot;config.json&quot; file there is the correct value on &quot;BotToken&quot;.
        /// </summary>
        internal static string invalid_token {
            get {
                return ResourceManager.GetString("invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 🇬🇧 English.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 🇮🇹 Italian.
        /// </summary>
        internal static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ❌ File must be smaller than 20MB. If your backup includes playlists, I suggest you to export them, delete them and re-send me the backup file.
        /// </summary>
        internal static string max_filesize {
            get {
                return ResourceManager.GetString("max_filesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 🔗 Here is the merged file!.
        /// </summary>
        internal static string merged_file {
            get {
                return ResourceManager.GetString("merged_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 🔗 Here is the merged file! I will keep it in my memory.
        /// </summary>
        internal static string merged_file_keep {
            get {
                return ResourceManager.GetString("merged_file_keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UserDataBackup_{0}_Merged.jwlibrary.
        /// </summary>
        internal static string merged_filename {
            get {
                return ResourceManager.GetString("merged_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A message from {0} has been dropped because the chat has been temporary banned.
        /// </summary>
        internal static string message_dropped {
            get {
                return ResourceManager.GetString("message_dropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a a callback query.
        /// </summary>
        internal static string message_type_callbackquery {
            get {
                return ResourceManager.GetString("message_type_callbackquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a a file.
        /// </summary>
        internal static string message_type_file {
            get {
                return ResourceManager.GetString("message_type_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a a message.
        /// </summary>
        internal static string message_type_text {
            get {
                return ResourceManager.GetString("message_type_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a a not handled content.
        /// </summary>
        internal static string message_type_unhandled {
            get {
                return ResourceManager.GetString("message_type_unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 👾 I&apos;ve checked, but I&apos;ve nothing yours in my memory.
        /// </summary>
        internal static string nothing_to_delete {
            get {
                return ResourceManager.GetString("nothing_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UserDataBackup_Old_Schema.jwlibrary.
        /// </summary>
        internal static string old_filename {
            get {
                return ResourceManager.GetString("old_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ❌ I cannot merge the last file you sent me with the one I had in my memory. This last one is created by an old version of JW Library and it should be updated in order to be processed.\n\nThe file attached to this message is the old file. If you want to merge it you should:\n- Backup up your current data from JW Library\n- Restore this old file from JW Library\n- Create a new backup and send it to me\n\nIn my memory I&apos;ve replaced the old file with the new one you sent me.
        /// </summary>
        internal static string old_schema_error {
            get {
                return ResourceManager.GetString("old_schema_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ❗️ Error while merging file: {0}.
        /// </summary>
        internal static string processing_error {
            get {
                return ResourceManager.GetString("processing_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 📥 I&apos;ve got the main file 📨 I will keep it in my memory.
        /// </summary>
        internal static string received_file1 {
            get {
                return ResourceManager.GetString("received_file1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 📥 I&apos;ve got the file 🔗 Now I merge it with the file in my memory… .
        /// </summary>
        internal static string received_file2 {
            get {
                return ResourceManager.GetString("received_file2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I received {0} from {1}: {2}.
        /// </summary>
        internal static string received_something {
            get {
                return ResourceManager.GetString("received_something", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hello {0}, I&apos;m @JWLMergeBot 🤖\nMy purpose is to merge two backup files of JW Library into a single one 🔗\n\nI work like this:\n1. You send me a file 📩\n2. I store it 📨\n3. You send me another file 📩\n4. I merge it with the first and then I send back to you the merged file 🔗\n\nObviously, sending me a file you agree that I store it 📝\nHow could I merge it if I don&apos;t store it? 🤪\nHowever you can delete it whenever you want with the appropriate command /delete 🗑\n\nPlease note! I don&apos;t currently suppo [stringa troncata]&quot;;.
        /// </summary>
        internal static string start_details {
            get {
                return ResourceManager.GetString("start_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stored files: {0}\nUsers:\n{1}.
        /// </summary>
        internal static string stat {
            get {
                return ResourceManager.GetString("stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ❌ I can only deal with JW Library backup files (*.jwlibrary).
        /// </summary>
        internal static string wrong_filetype {
            get {
                return ResourceManager.GetString("wrong_filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
